### ISSUE TITLE
Switch Generator value

### ISSUE THREAD

**Issue by Ryuno-Ki** [Ryuno-Ki/eleventy-plugin-meta-generator#81]
https://github.com/11ty/eleventy/issues/1217 asked to change the value to 

> `<meta name="generator" content="11ty v0.11.0" />`
> 
> value format being: 11ty + space + v + (semver in x.y.z format)

**Comment by Ryuno-Ki** [comment]
Fixed with https://github.com/Ryuno-Ki/eleventy-plugin-meta-generator/commit/5cb4352c910d69cd50c8fa22285d069d16254187

@brycewray @revelt @nhoizey @binyamin @zachleat

Looking into the Eleventy-provided helper next.

**Comment by nhoizey** [comment]
I guess you mean "Eleventy" instead of "11ty", as currently `{{ eleventy.generator }}` gives `Eleventy v1.0.1`, right?

**Comment by Ryuno-Ki** [comment]
Yeah, I'm about to deprecate this package. It's better to align on the core here.

**Comment by Ryuno-Ki** [comment]
This package is now deprecated. This repository will be archived and the removed from the plugin list.

https://www.npmjs.com/package/eleventy-plugin-meta-generator
