### ISSUE TITLE
Request: Add .11ty.js examples to README

### ISSUE THREAD

**Issue by brycewray** [Ryuno-Ki/eleventy-plugin-meta-generator#82]
As mentioned in https://github.com/11ty/eleventy/issues/1217, I request that the README include examples for `.11ty.js` templating, in addition to the existing Nunjucks and Liquid templating examples. Thanks!

**Comment by Ryuno-Ki** [comment]
This package is now deprecated. This repository will be archived and the removed from the plugin list.

https://www.npmjs.com/package/eleventy-plugin-meta-generator
